const acquisitionsData = [
    {date: '23 août 2005', company: 'facebook.com', activity: 'AboutFace'},
    {date: '19 juillet 2007', company: 'Parakey', activity: "Système d'exploitation en ligne"},
    {date: '23 juin 2008', company: 'ConnectU', activity: 'Réseautage social'},
    {date: '10 septembre 2009', company: 'FriendFeed', activity: 'Agrégateur\xa0de\xa0réseaux sociaux'},
    {date: '19 février 2010', company: 'Octazen', activity: 'Importation de contacts'},
    {date: '2 mars 2010', company: 'Divvyshot', activity: 'Gestion de photos'},
    {date: '13 mai 2010', company: 'Friendster patents', activity: 'Propriété intellectuelle'},
    {date: '26 mai 2010', company: 'ShareGrove', activity: 'Conversation privées et forums'},
    {date: '8 juillet 2010', company: 'Nextstop', activity: 'Recommandation de voyages'},
    {date: '15 août 2010', company: 'Chai Labs', activity: 'Applications en lignes'},
    {date: '20 août 2010', company: 'Hot Potato', activity: 'Check-in et statuts'},
    {date: '29 octobre 2010', company: 'Drop.io', activity: 'Hébergement et partage de fichiers'},
    {date: '15 novembre 2010', company: 'Nom de domaine fb.com', activity: "Racheté auprès de l'American Farm Bureau Federation"},
    {date: '25 janvier 2011', company: 'Rel8tion', activity: 'Publicité en ligne'},
    {date: '2 mars 2011', company: 'Beluga', activity: 'Messagerie de groupe'},
    {date: '20 mars 2011', company: 'Snaptu', activity: "Développement d'applications mobiles"},
    {date: '24 mars 2011', company: 'RecRec', activity: nan},
    {date: '27 avril 2011', company: 'DayTum', activity: nan},
    {date: '9 juin 2011', company: 'Sofa', activity: 'Design logiciel'},
    {date: '9 juin 2011', company: 'MailRank', activity: "Gestion d'email"},
    {date: '2 août 2011', company: 'Push Pop Press', activity: 'Publication en ligne'},
    {date: '10 octobre 2011', company: 'Friend.ly', activity: 'Service de questions-réponses'},
    {date: '8 novembre 2011', company: 'Strobe', activity: 'Applications mobiles en html5'},
    {date: '2 décembre 2011', company: 'Gowalla', activity: nan},
    {date: '9 avril 2012', company: 'Instagram', activity: 'Partage de photos et vidéos'},
    {date: '13 avril 2012', company: 'Tagtile', activity: nan},
    {date: '15 mai 2012', company: 'Lightbox.com', activity: nan},
    {date: '21 mai 2012', company: 'Karma', activity: nan},
    {date: '18 juin 2012', company: 'Face.com', activity: nan},
    {date: '14 juillet 2012', company: 'Spool', activity: nan},
    {date: '20 juillet 2012', company: 'Acrylic Software', activity: nan},
    {date: '24 août 2012', company: 'Threadsy', activity: nan},
    {date: '28 février 2013', company: 'Atlas', activity: nan},
    {date: 'mars 2013', company: 'Osmeta', activity: nan},
    {date: '14 mars 2013', company: 'Hot Studio', activity: nan},
    {date: '23 avril 2013', company: 'Spaceport', activity: nan},
    {date: '25 avril 2013', company: 'Parse', activity: nan},
    {date: '18 juillet 2013', company: 'Monoidics', activity: nan},
    {date: '12 août 2013', company: 'Jibbigo', activity: nan},
    {date: '13 octobre 2013', company: 'Onavo', activity: 'VPN'},
    {date: '17 décembre 2013', company: 'SportStream', activity: nan},
    {date: '8 janvier 2014', company: 'Little Eye Labs', activity: nan},
    {date: '13 janvier 2014', company: 'Branch', activity: 'Plateforme de commentaires et discussions'},
    {date: '19 février 2014', company: 'WhatsApp', activity: 'Messagerie instantanée'},
    {date: '26 février 2014', company: 'Oculus VR', activity: 'Réalité virtuelle'},
    {date: '24 avril 2014', company: 'Moves', activity: "Application de fitness et de tracking d'activité"},
    {date: '3 juin 2014', company: 'Pryte', activity: 'Connexion à la demande'},
    {date: '2 juillet 2014', company: 'LiveRail', activity: 'Start-up de pubs vidéos'},
    {date: '5 janvier 2015', company: 'Wit.ai', activity: 'Applications de reconnaissance vocale'},
    {date: '8 janvier 2015', company: 'Quickfire Networks', activity: 'Video Compression'},
    {date: '14 mars 2015', company: 'TheFind, Inc.', activity: 'Ecommerce'},
    {date: '26 mai 2015', company: 'Surreal Vision', activity: 'Réalité augmentée'},
    {date: '18 mai 2020', company: 'Giphy', activity: 'Librairie de Gifs'},
    {date: '18 juin 2020', company: 'Mapillary', activity: 'Logiciel en ligne de partage de photos géolocalisées'},
    {date: '22 juin 2020', company: 'Ready at Dawn', activity: 'studio américain de développement de jeux vidéo'},
    {date: '18 septembre 2020', company: 'Lemnis Technologies', activity: 'technologie compagnie'},
    {date: '30 novembre 2020', company: 'kustomer', activity: 'platforme CRM'},
    {date: '30 avril 2021', company: 'Downpour Interactive', activity: 'Développeur de jeux vidéo'},
    {date: '4 juin 2021', company: 'Unit 2 Games', activity: 'Développeur de logiciels'},
    {date: '11 octobre 2021', company: 'BigBox VR', activity: 'Studio de développement de jeu vidéo'},
    {date: '29 octobre 2021', company: 'AI.Reverie', activity: 'I.A developement'},
    {date: '1 novembre 2021', company: 'Within', activity: "développeur de l'application de fitness"},
    {date: '8 avril 2022', company: 'Presize', activity: "production et l'ingénierie de composants mécaniques"},
    {date: 'septembre 2022', company: 'Lofelt', activity: 'Développeur de logiciels'},
    {date: '11 octobre 2022', company: 'Armature Studio', activity: 'studio de développement de jeux vidéo'},
    {date: '11 octobre 2022', company: 'Camouflaj', activity: 'Développeur de jeux vidéo'}
];